### PR TITLE
SLOSH Integration

### PR DESCRIPTION
**Pull request by mtyhon**
I've added code for SLOSH, which allows you to call or train a 2D deep learning classifier and regressor. Utilities to create the 2D images are also provided. Currently it supports LC classification, with SC coming soon.

### CODE REVIEW

**Comment by rhandberg** [comment]
Hi Marc,
Very nice that you have managed to get SLOSH integrated!
I do have some small comments before we merge it in:

- [ ] Remove the ".idea" directory - I assume this is something related to your editor/IDE, so we shouldn't include that in the repo.
- [ ] Please put any large files (like things in starclass/SLOSH/sample_data) under Git LFS (https://git-lfs.github.com/) and we avoid having the repo growing very big with these large files. You simply add the directory to the .gitattributes file.

Cheers,
Rasmus

**Comment by mtyhon** [comment]
Hi Rasmus,

I've implemented them. Do let me know if there are other issues as well.

Cheers,
Marc

**Comment by rhandberg** [comment]
Hi Marc,

Great - good work! :-)

Could you enlighten me on what the difference is between the `SLOSH_Regressor` and `SLOSH_Classify` classes? For your classifier, you should only have one class (SLOSHClassifier?), which as a minimum should implement a `do_correction` and `train` method.

Have a look at the minimum example classifier here: 
https://github.com/tasoc/starclass/blob/devel/starclass/example/ExampleClassifier.py

Cheers,
Rasmus

**Comment by mtyhon** [comment]
Hi Rasmus,
`SLOSH_Classify` detects whether or not solar-like oscillations are present (classification), while `SLOSH_Regressor` estimates nu_max of the star. They are made separate because they train differently from one another. From what I understand, the former is more important for the top-level, so if `SLOSH_Regressor` isn't needed I can remove it from the code and save it for later.

I have renamed the methods in the classifier class to `do_classify` and `train` as well.

Cheers,
Marc

**Comment by rhandberg** [comment]
Hi Marc,

Okay, great! 

As you say `SLOSH_Classify` is the most important thing for the Level 1 classification, so let's concentrate on that one for now. But just keep `SLOSH_Regressor` in there. We will have to think a little bit about how we should return derived parameters (like numax) from the different classifiers at some point anyway...

You need to make sure that the `do_classify` and `train` methods accepts the same kind of input as is specified in the ExampleClassifier. `do_classify`  should for example accept a dictionary of "features" (including lightcurve and power density spectrum) and return a dictionary of the classifications and their probability.

Does that make sense?

Cheers,
Rasmus

**Comment by mtyhon** [comment]
Hi Rasmus,

For brevity I have removed `SLOSH_Regressor` from the code. The class is fairly similar to `SLOSH_Classifier` so it will not be too difficult to re-introduce it when it may be needed in future. I have changed the inputs and outputs for `do_classify` and `train` to dicts, following ExampleClassifier. I am not too certain of the keys for the feature dictionary so I have used temporary names, in particular:

features['frequency'] - frequency array for the star
features['power_density'] - PSD array
features['star_id'] - star TIC

Cheers,
Marc

**Comment by rhandberg** [comment]
Very nice :-)

Its not exactly the right key-names for the features dict, but I dont blame you for that (it's really poorly documented right now). But I think it would be easy for me to just merge and change those few keys for you...

Excellent work! I will merge it now and test it a bit...

Cheers,
Rasmus

**Pull request merged**
