### PR TITLE
Updating keras dependencies to tf.keras

### PR DESCRIPTION
**Pull request by mtyhon**
The explicit dependencies on keras have been replaced in favour of tf.keras, which supports Tensorflow 2. The regularization parameter for training SLOSH has been updated in accordance the testing done by @jsk389.

### CODE REVIEW

**Comment by rhandberg** [comment]
Hi Marc,
Looks good! Could I just get you to update the `requirements.txt` file, where I guess you have to remove `keras` and update the `tensorflow` version to whatever you know is working (latest one?)

**Comment by mtyhon** [comment]
Hi Rasmus, 

I've made the changes to requirements file.

**Comment by rhandberg** [comment]
Hi Marc, Great! We do however still get one error in the Travis CI checks (as you can properly see). We have currently pinned scipy to version 1.3.3, but the new tensorflow requires 1.4.1:
`tensorflow 2.3.0 requires scipy==1.4.1, but you'll have scipy 1.3.3 which is incompatible.`

Maybe we could just try to change the required scipy version to 1.4.1 as well, and then test if things are still working... Hopefully there haven't been too many breaking changes in scipy that the rest of the code rely on...

**Comment by rhandberg** [comment]
Actually just tested that on my machine, and of course lightkurve doesn't like SciPy 1.4.1 for some reason... Maybe just go all the way to the newest version `scipy ==1.5.2` in `requirements.txt`?

**Comment by rhandberg** [comment]
Just researched a little bit (i.e. read tensorflow issues page) and found that this is actually a small bug the was fixed in tensorflow 2.3.1, so maybe we could just update to `tensorflow == 2.3.1` in `requirements.txt`?

**Comment by mtyhon** [comment]
By looking over the differences between 2.3.0 and 2.3.1, there shouldn't be any difference with the SLOSH implementation so it should be fine. I have updated the requirements file.

**Comment by rhandberg** [comment]
That definitely helped... Now it looks like everything installs on Travis CI at least... But unfortunately it still fails when it tries to actually import that package later on:

```
2020-10-05 13:58:52.335548: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-05 13:58:52.335593: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "run_download_cache.py", line 6, in <module>
    import starclass
  File "/home/travis/build/tasoc/starclass/starclass/__init__.py", line 9, in <module>
    from .SLOSH import SLOSHClassifier
  File "/home/travis/build/tasoc/starclass/starclass/SLOSH/__init__.py", line 5, in <module>
    from .SLOSH import SLOSHClassifier
  File "/home/travis/build/tasoc/starclass/starclass/SLOSH/SLOSH.py", line 16, in <module>
    from . import SLOSH_prepro as preprocessing
  File "/home/travis/build/tasoc/starclass/starclass/SLOSH/SLOSH_prepro.py", line 12, in <module>
    from tf.keras.layers import Dropout, MaxPool2D, Flatten, Conv2D, LeakyReLU, Dense
ModuleNotFoundError: No module named 'tf'
```

I don't know if this is something specific to Travis CI (looking at the two warnings) or something else in the actual code... Does it need to be  `from tensorflow.keras.layes import ...` (without the "tf" short-hand)?

Have you ever seen this before?

**Comment by mtyhon** [comment]
I believe that was an improper way to call the import, my mistake! I have removed the tf short-hand, which should clear up any confusion.

**Review by rhandberg — APPROVED** [review]
Looking good! Everything seems to be working now. Only complaint from the checks are missing tests, but this is not specific to SLOSH, but rather a larger issue we should look at later on.

**Pull request merged**
